#! /bin/sh

sxhkd &

~/.config/polybar/./launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X
xrandr --set-primary eDP-1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Zathura desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Thunar state=floating

xinput set-prop "Microsoft Surface Type Cover Touchpad" "Coordinate Transformation Matrix" 2 0 0 0 2 0 0 0 1
xinput set-prop "Microsoft Surface Type Cover Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "Microsoft Surface Type Cover Touchpad" "libinput Natural Scrolling Enabled" 1
xsetroot -cursor_name left_ptr &
feh --bg-fill ~/Pictures/Wallpapers/monochrome.png
picom
